version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm install
      - run: npm test
  two:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "A more familiar hi"  
      
workflows:
  version: 2
  test_and_two:
    jobs:
      - test
      - two:
          requires:
            - test