version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install
  two:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "A more familiar hi"  
      
workflows:
  version: 2
  test_and_two:
    jobs:
      - test
      - two:
          requires:
            - test